# Generated by Django 5.2.15 on 2026-07-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='securityevent',
            name='is_triaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='rssi',
            field=models.IntegerField(blank=True, help_text='Signal strength indicator in dBm', null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk / Tactical Threat')], default='LOW', max_length=20),
        ),
    ]
