from dataclasses import dataclass, asdict, field
from datetime import datetime
from typing import Any, Dict, Optional
import uuid


@dataclass
class EventEnvelope:
    """
    Unified event schema for Kafka + MQTT + internal event bus.
    """

    event_id: str
    event_type: str
    source: str

    timestamp: str
    version: str = "1.0"

    correlation_id: Optional[str] = None
    trace_id: Optional[str] = None

    payload: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self):
        return asdict(self)

    @staticmethod
    def create(
        event_type: str,
        payload: Dict[str, Any],
        source: str,
        correlation_id: str = None,
        trace_id: str = None,
        metadata: Dict[str, Any] = None,
    ):
        return EventEnvelope(
            event_id=str(uuid.uuid4()),
            event_type=event_type,
            source=source,
            timestamp=datetime.utcnow().isoformat(),
            version="1.0",
            correlation_id=correlation_id,
            trace_id=trace_id,
            payload=payload,
            metadata=metadata or {},
        )


@dataclass
class SecurityEvent:
    """
    Security alert event generated by sensors / detection modules.
    """

    event_type: str
    severity: str
    description: str = ""
    rssi: Optional[int] = None
    source: str = "main"
    timestamp: datetime = field(default_factory=datetime.utcnow)





